version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - symfony
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql://mysql_user:mysql_password@db:3306/mysql_db"

  web:
    image: nginx:latest
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./deployment/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - symfony

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
